{"errors":["In the world's resolve_all_references step: In 'reference_outer_non_positive_arg': Reference error: In '@OUTER:0': invalid '@OUTER:0' found at position 0: Argument to '@OUTER' must be positive number. Got '0', which is less than 1"]}